name: 🔧 General Task
description: 일반적인 작업 요청 (style, test, chore, comment, design, remove, rename)
title: '[] '
labels: ['task']
body:
  - type: markdown
    attributes:
      value: |
        일반적인 작업을 위한 이슈를 작성해주세요.

  - type: dropdown
    id: task-type
    attributes:
      label: 작업 유형
      description: 어떤 종류의 작업인지 선택해주세요.
      options:
        - style - 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
        - test - 테스트 코드, 리팩토링 테스트 코드 추가
        - chore - 빌드 업무 수정, 패키지 매니저 수정
        - comment - 필요한 주석 추가
        - design - CSS나 디자인 변경, 이미지 추가
        - remove - 파일 삭제
        - rename - 파일 경로 변경 혹은 파일 이름 변경
    validations:
      required: true

  - type: textarea
    id: task-description
    attributes:
      label: 작업 설명
      description: 수행할 작업에 대해 자세히 설명해주세요.
      placeholder: 어떤 작업을 수행하고 싶으신가요?
    validations:
      required: true

  - type: textarea
    id: target-files
    attributes:
      label: 대상 파일/폴더
      description: 작업할 파일이나 폴더를 명시해주세요.
      placeholder: |
        - src/components/Button.tsx
        - styles/global.css
        - tests/
    validations:
      required: false

  - type: textarea
    id: task-details
    attributes:
      label: 작업 세부사항
      description: 구체적인 작업 내용이나 요구사항을 작성해주세요.
      placeholder: 구체적으로 어떤 작업을 해야 하나요?
    validations:
      required: true

  - type: checkboxes
    id: task-checklist
    attributes:
      label: 작업 체크리스트
      description: 완료해야 할 작업들을 체크리스트로 작성해주세요.
      options:
        - label: 작업 1
        - label: 작업 2
        - label: 작업 3
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 작업의 우선순위를 선택해주세요.
      options:
        - High (높음)
        - Medium (보통)
        - Low (낮음)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 스크린샷, 참고 자료, 관련 링크 등을 첨부해주세요.
      placeholder: 추가적인 정보가 있다면 여기에 작성해주세요.
    validations:
      required: false
