export type ReviewTag =
  | 'GOOD_COMMUNICATION'
  | 'KEEPS_PROMISES'
  | 'RESPONSIBLE'
  | 'POSITIVE_ENERGY'
  | 'PROBLEM_SOLVER'
  | 'RESPECTS_OPINIONS'
  | 'POOR_COMMUNICATION'
  | 'IGNORES_OPINIONS'
  | 'LACKS_RESPONSIBILITY'
  | 'NEGATIVE_INFLUENCE'
  | 'POOR_PROBLEM_SOLVING'
  | 'BREAKS_PROMISES';
