name: CD - Dev Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "배포 시작"
            cd /root/dodream-dev

            echo "최신 코드 가져오기"
            git pull origin develop

            echo "의존성 설치"
            npm ci

            echo "프로젝트 빌드"
            npm run build

            echo "서버 재시작"
            pm2 restart dev --update-env
            pm2 save

            echo "✅ 개발 서버 배포 완료"
            pm2 info dev
